<?php
 /**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * @category   Persian Magento
 * @package    Persianmagento_Zarinpalzar
 * @copyright  Copyright (c) 1396 Persian Magento (http://www.persian-magento.ir)
 */ 
?>

<fieldset class="form-list">
    <?php $_code=$this->getMethodCode() ?>
    <ul id="payment_form_<?php echo $_code ?>" style="display:none">
        <li>
            <?php echo $this->__('You will be redirected to Zarinpal website when you place an order.') ?><br />
        </li>
        <div style="padding:10px 15px 15px;">
          <img src="<?php echo $this->getPaymentImageSrc(); ?>" alt="<?php echo $this->__('Zarinpal payment methods') ?>" />
        </div>
    </ul>
</fieldset>