<?php
 /**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * @category   Persian Magento
 * @package    Persianmagento_Zarinpalzar
 * @copyright  Copyright (c) 1396 Persian Magento (http://www.persian-magento.ir)
 */ 
?>

<style type="text/css">
.titr {
	font-family: Tahoma;
	font-size: 14px;
}
</style>
<center>
    <span class="titr"><b>در حال اتصال به سایت زرین پال</b>
    <br />لطفا منتظر بمانید 
    </span>
</center>
<form id="Persianmagento_Zarinpalzar" action="<?php echo $this->getFormAction();?>" method="POST">
<?php if (is_array($this->getFormData())): ?>
    <?php foreach ($this->getFormData() as $name => $value): ?>
        <input type="hidden" name="<?php echo $name; ?>" value="<?php echo $value; ?>"/>
    <?php endforeach; ?>
<?php endif; ?>
</form>

<script type="text/javascript">
//<![CDATA[
    var paymentform = document.getElementById('Persianmagento_Zarinpalzar');
    window.onload = paymentform.submit();
//]]>
</script>
