<?php
 /**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * @category   Persian Magento
 * @package    Persianmagento_Zarinpalweb
 * @copyright  Copyright (c) 1396 Persian Magento (http://www.persian-magento.ir)
 */ 
?>

<?php 
	
	echo $this->getMethod()->getTitle() . '<br/>';
	
	if ($this->getInfo()->getLastTransId() == '') {
		echo '<em>' . $this->__('You will be redirected to Zarinpal website when you place an order.') . '</em>';
	} else {
		echo $this->__('Zarinpal Transaction ID: %s', $this->htmlEscape($this->getInfo()->getLastTransId())) . '<br/>';
	}

?>